### ISSUE TITLE
Can I be contributor?

### ISSUE THREAD

**Issue by Ashwin-Paudel** [AymenSekhri/CyanOS#14]
I want to help build this OS

**Comment by Ashwin-Paudel** [comment]
Also, where is the .iso file?

**Comment by AymenSekhri** [comment]
> I want to help build this OS
Sure thing, pick up something you like and start working on it.

> Also, where is the .iso file?
Well, there is not much to show in the iso release yet, except few basic commands. So I didn't bother uploading it.

**Comment by Ashwin-Paudel** [comment]
ok thanks!
